"""views as a list of viewers added

Revision ID: 0d8dc99933f1
Revises: 25fca66ed3ce
Create Date: 2025-03-08 12:13:02.031591

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d8dc99933f1"
down_revision: Union[str, None] = "25fca66ed3ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("android_metadata")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "views", existing_type=sa.INTEGER(), type_=sa.JSON(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "views", existing_type=sa.JSON(), type_=sa.INTEGER(), existing_nullable=True
        )

    op.create_table("android_metadata", sa.Column("locale", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
