"""in User model reactions added with backref user

Revision ID: 25fca66ed3ce
Revises: d3468e24ce21
Create Date: 2025-03-07 15:00:58.242785

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25fca66ed3ce"
down_revision: Union[str, None] = "d3468e24ce21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
