"""title views author to post

Revision ID: 28dd40239fc4
Revises: efb40236c539
Create Date: 2025-03-05 17:56:09.809460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import Inspector

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28dd40239fc4"
down_revision: Union[str, None] = "efb40236c539"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Получаем доступ к инспектору для проверки существования таблицы
    inspector = Inspector.from_engine(op.get_bind())
    if "android_metadata" in inspector.get_table_names():
        op.drop_table("android_metadata")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column("author", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("views", sa.Text(), nullable=True))
        batch_op.create_foreign_key("fk_author_user", "users", ["author"], ["username"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_author_user", type_="foreignkey")
        batch_op.drop_column("views")
        batch_op.drop_column("author")
        batch_op.drop_column("title")

    op.create_table("android_metadata", sa.Column("locale", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
