"""singletone server

Revision ID: 859ecc97ce40
Revises: 6017a83958a7
Create Date: 2025-03-05 14:13:43.945878

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "859ecc97ce40"
down_revision: Union[str, None] = "6017a83958a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("android_metadata")
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.alter_column(
            "server_name", existing_type=sa.VARCHAR(length=120), nullable=True
        )
        batch_op.alter_column(
            "color_scheme", existing_type=sa.VARCHAR(length=7), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("servers", schema=None) as batch_op:
        batch_op.alter_column(
            "color_scheme", existing_type=sa.VARCHAR(length=7), nullable=False
        )
        batch_op.alter_column(
            "server_name", existing_type=sa.VARCHAR(length=120), nullable=False
        )

    op.create_table("android_metadata", sa.Column("locale", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
