"""big update server model has addded

Revision ID: abfdbc6d210f
Revises: 28dd40239fc4
Create Date: 2024-04-04 23:38:54.211367

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abfdbc6d210f"
down_revision: Union[str, None] = "28dd40239fc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_name", sa.String(length=120), nullable=False),
        sa.Column("server_description", sa.String(length=1000), nullable=True),
        sa.Column("server_background", sa.String(length=256), nullable=True),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("color_scheme", sa.String(length=7), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("android_metadata")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column(
            "views", existing_type=sa.TEXT(), type_=sa.JSON(), existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.alter_column(
            "views", existing_type=sa.JSON(), type_=sa.TEXT(), existing_nullable=True
        )

    op.create_table("android_metadata", sa.Column("locale", sa.TEXT(), nullable=True))
    op.drop_table("servers")
    # ### end Alembic commands ###
