"""Reaction and backref to Messaga

Revision ID: d3468e24ce21
Revises: 859ecc97ce40
Create Date: 2025-03-07 14:52:52.998349

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3468e24ce21"
down_revision: Union[str, None] = "859ecc97ce40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("emoji", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("post_replies")
    op.drop_table("android_metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("android_metadata", sa.Column("locale", sa.TEXT(), nullable=True))
    op.create_table(
        "post_replies",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("author", sa.VARCHAR(length=200), nullable=True),
        sa.Column("created", sa.DATETIME(), nullable=True),
        sa.Column("images", sqlite.JSON(), nullable=True),
        sa.Column("views", sqlite.JSON(), nullable=True),
        sa.Column("post_id", sa.INTEGER(), nullable=False),
        sa.Column("parent_reply_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author"], ["users.username"], name="fk_post_replies_author_users"
        ),
        sa.ForeignKeyConstraint(
            ["parent_reply_id"],
            ["post_replies.id"],
            name="fk_post_replies_parent_reply_id_post_replies",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name="fk_post_replies_post_id_posts"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_post_replies_user_id_users"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_post_replies"),
    )
    op.drop_table("reaction")
    # ### end Alembic commands ###
