"""Post separated on Post and PostReply

Revision ID: f3ddb1b1806a
Revises: 859ecc97ce40
Create Date: 2025-03-07 00:52:06.371663

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3ddb1b1806a"
down_revision: Union[str, None] = "859ecc97ce40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_replies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("images", sa.JSON(), nullable=True),
        sa.Column("views", sa.JSON(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("parent_reply_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author"],
            ["users.username"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_reply_id"],
            ["post_replies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("android_metadata")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("text", sa.Text(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("post_id")
        batch_op.drop_column("content")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("post_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, "posts", ["post_id"], ["id"])
        batch_op.drop_column("text")

    op.create_table("android_metadata", sa.Column("locale", sa.TEXT(), nullable=True))
    op.drop_table("post_replies")
    # ### end Alembic commands ###
